"""
Scan Baserow database tables and print link_row relationships.
Helps understand how products connect to brands, categories, etc.

Usage:
  python discover_baserow_relations.py
  python discover_baserow_relations.py --save docs/BASEROW_RELATIONS.generated.md
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from baserow_client import BaserowClient
from config import load_settings

# Known tables in database 181 (from API field scans + handover)
CORE_TABLES = {
    802: "productsDetails",
    805: "brands",
    806: "productCategory",
    807: "subCategory",
    804: "productTrend (?) ",
    808: "styleType",
    812: "stores",
    817: "productsDetails (secondary?)",
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Discover Baserow link_row relations")
    p.add_argument(
        "--save",
        metavar="PATH",
        help="Write markdown report to this file",
    )
    p.add_argument(
        "--tables",
        default="802,805,806,807,804,808,812,817",
        help="Comma-separated table IDs to scan",
    )
    return p.parse_args()


def scan_table(client: BaserowClient, table_id: int) -> dict:
    fields = client.get_table_fields(table_id)
    name = CORE_TABLES.get(table_id, f"table_{table_id}")
    links = []
    others = []
    for f in fields:
        entry = {
            "name": f.get("name"),
            "type": f.get("type"),
            "api_key": f"field_{f['id']}",
            "field_id": f["id"],
        }
        if f["type"] == "link_row":
            entry["links_to_table"] = f.get("link_row_table_id")
            links.append(entry)
        else:
            others.append(entry)
    return {"table_id": table_id, "name": name, "links": links, "other_count": len(others)}


def build_report(scans: list[dict], settings) -> str:
    lines = [
        "# Baserow relations (database 181)",
        "",
        f"Instance: `{settings.baserow_url}`",
        "",
        "Generated by `discover_baserow_relations.py`.",
        "",
        "## How link_row works in Baserow",
        "",
        "- A **link_row** field connects a row in table A to row(s) in table B.",
        "- In the API you send **target row IDs** as a JSON array: `[5]` or `[5, 12]`.",
        "- The same relationship can appear on **both tables** (product → brand and brand → products).",
        "- Our scraper sets links on the **product row** when creating/updating; it also updates **brand.productsDetails**.",
        "",
        "## Core tables (scraping)",
        "",
        "| Table ID | Name | Role |",
        "|----------|------|------|",
        f"| {settings.products_table_id} | productsDetails | **Product rows** (scrape target) |",
        f"| {settings.brands_table_id} | brands | Brand list + link back to products |",
        f"| {settings.category_table_id} | productCategory | Top category (Banken, Stoelen, …) |",
        f"| {settings.subcategory_table_id} | subCategory | Sub category (Eetkamerstoelen, …) |",
        "",
        "## When you add ONE product (recommended links)",
        "",
        "Set these on the **productsDetails** row (table 802):",
        "",
        "| Field | Links to table | API value | Source from scrape |",
        "|-------|----------------|-----------|-------------------|",
        "| `Brand_table` | 805 brands | `[brand_row_id]` | Brand name -> lookup row in brands |",
        "| `product_category` | 806 productCategory | `[category_row_id]` | Breadcrumb / mapping |",
        "| `sub_category` | 807 subCategory | `[sub_row_id]` | Breadcrumb / mapping |",
        "",
        "Also set text fields: `product_name`, `product_description`, `product_url`, `source_product_*`, files, etc.",
        "",
        "Then update **brands** row: `productsDetails` field += new product row id (our `link_product_to_brand`).",
        "",
        "---",
        "",
        "## All link_row fields per table",
        "",
    ]

    for scan in scans:
        lines.append(f"### Table {scan['table_id']} — {scan['name']}")
        lines.append("")
        if not scan["links"]:
            lines.append("(no link_row fields)")
            lines.append("")
            continue
        lines.append("| Field | API key | Links to table ID |")
        lines.append("|-------|---------|-------------------|")
        for link in scan["links"]:
            target = link.get("links_to_table", "?")
            target_name = CORE_TABLES.get(target, "")
            extra = f" ({target_name})" if target_name else ""
            lines.append(
                f"| {link['name']} | `{link['api_key']}` | {target}{extra} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Relation diagram (core)",
            "",
            "```mermaid",
            "erDiagram",
            "    brands ||--o{ productsDetails : productsDetails",
            "    productCategory ||--o{ subCategory : subCategory",
            "    productCategory ||--o{ productsDetails : productsDetails",
            "    subCategory ||--o{ productsDetails : productsDetails",
            "    productsDetails }o--|| brands : Brand_table",
            "    productsDetails }o--o| productCategory : product_category",
            "    productsDetails }o--o| subCategory : sub_category",
            "```",
            "",
            "## What our scraper does (`product_baserow.py`)",
            "",
            "1. `POST/PATCH` row on table **802** with text + file fields.",
            "2. `Brand_table` = `[brand_id]`.",
            "3. `product_category` / `sub_category` = resolved IDs from tables 806/807.",
            "4. `PATCH` brand row on **805**: append product id to `productsDetails` (field_8326).",
            "",
            "## API examples",
            "",
            "```http",
            "POST /api/database/rows/table/802/",
            "Authorization: Token YOUR_DATABASE_TOKEN",
            "Content-Type: application/json",
            "",
            "{",
            '  "field_8224": "Benno spiegel",',
            '  "field_8229": "https://www.spectrumdesign.nl/collectie/benno-spiegel",',
            '  "field_8253": [1],',
            '  "field_8240": [5],',
            '  "field_8241": [20]',
            "}",
            "```",
            "",
            "Upsert key: `field_8229` (`product_url`) — same URL → update existing row.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    try:
        settings = load_settings()
    except ValueError as exc:
        print(f"Config error: {exc}", file=sys.stderr)
        return 1

    client = BaserowClient(settings)
    table_ids = [int(x.strip()) for x in args.tables.split(",") if x.strip()]

    scans = []
    for tid in table_ids:
        try:
            scans.append(scan_table(client, tid))
            print(f"OK table {tid} ({CORE_TABLES.get(tid, '?')})")
        except Exception as exc:
            print(f"SKIP table {tid}: {exc}", file=sys.stderr)

    report = build_report(scans, settings)
    try:
        print("\n" + report)
    except UnicodeEncodeError:
        print("\n(report contains Unicode; see --save file)")

    if args.save:
        path = Path(args.save)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(report, encoding="utf-8")
        print(f"\nSaved: {path.resolve()}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
